services:
  timenet-flow-control:
    build: .
    container_name: timenet-flow-control-config
    ports:
      - "3002:3000"
    volumes:
      - flow-control-data:/data
    environment:
      - PORT=3000
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin@111
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true

volumes:
  flow-control-data:

networks:
  dokploy-network:
    external: true
